In [11]:
class demo:
    def test(self):
        print("test() for the class and method")
        
        return
obj=demo()
obj.test()

test() for the class and method


In [14]:
def test():
        print("test() for function")
        return
test()    

test() for function


In [2]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [7]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2      
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [21]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
    def isemployee(self):
        return True
emp=person("vasudha")
print(emp.getname(),emp.isemployee())
emp1=employee("madhuri")
print(emp1.getname(),emp1.isemployee())

vasudha False
madhuri True


In [23]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [24]:
import numpy as np
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int64


In [29]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [30]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [34]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.3254845  5.20738479 4.48016565 5.96967496 5.05351052 4.72835029
 5.14307663 4.18535726 6.05163508 4.90152156]


In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [37]:
np.zeros(((2,2)),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [38]:
np.ones(((4,3)),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [47]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [9]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 5  5  5  5]
 [ 1  1  1 16]]


In [4]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [8]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [21]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row =",a1[0])

first row = [1 2 3]


In [20]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row =",a1[1])

second row = [4 5 6]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row =",a1[:,1])

slicing row = [2 5]


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column =",a1[:,2])

slicing last column = [3 6]


In [17]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column =",a1[1,:2])

row and column = [4 5]


In [22]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column =",a1[1,:1])

row and column = [4]


In [25]:
a1=np.array([(1,2,3),(4,5,6)])
print("row =",a1[1,:])

row = [4 5 6]


In [34]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value =",np.min(a1))
print("max value =",np.max(a1))
print("mean value =",np.mean(a1))
print("median value =",np.median(a1))

[4.09016131 5.26153775 5.29354039 4.23983117 4.31008707 4.51422851
 4.99328644 5.15282444 5.85748913 3.97819164]
min value = 3.9781916393953285
max value = 5.857489133422587
mean value = 4.769117784469306
median value = 4.753757475319656


In [35]:
c1=np.array([1,2])
c2=np.array([3,4])
np.dot(c1,c2)

11

In [36]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(5,6),(7,8)])
np.dot(c1,c2)

array([[19, 22],
       [43, 50]])

In [37]:
c1=np.array([(1,5),(6,9)])
c2=np.array([(1,6),(7,2)])
np.matmul(c1,c2)

array([[36, 16],
       [69, 54]])

In [51]:
def frequency(str):
    for i in range (10):
        cnt=0
        for j in str:
            if(j.isdigit()):
                if(i==int(j)):
                    cnt=cnt+1
        print(cnt)  
frequency("213abc456def111")       

0
4
1
1
1
1
1
0
0
0
